"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3Ou93NEzRjT
 */
import { Button } from "@/components/ui/button"
import { Navbar } from "@/components/navbar"
import Image from "next/image"
import Reviews from "@/components/component/reviews";

export function Home() {
  return (
    <div className="relative">
      <Navbar />
      <main className="pt-16" 
      >
      
        <section className="container mx-auto mt-8 px-4">        
          <h1 className="text-3xl font-thin text-center text-grey-400">Intelli Concierge</h1>
          <p className="mt-4 text-center text-6xl font-bold text-blue-600 mb-8 bg-clip-text bg-gradient-to-r from-blue-500 to-teal-400">Automate customer support responses.</p>
          <p className="text-center text-lg font-bold font-medium text-gray-800">
            Improve customer experience by automating responses to frequently asked questions. Handle responses across 3 different channels seamlessly with
            one platform. All this power is available at an affordable price.
          </p>
          <div className="mt-6 flex justify-center space-x-4">
          <Button
          className="px-6 py-3 text-md font-medium text-white bg-gray-800 rounded-md shadow-sm hover:bg-gray-900"
          >
            <a
              href="/chat"
            >
             Chat with our assistant
            </a>
            
            </Button>
            <Button
          className="px-6 py-3 text-md font-medium text-white bg-blue-600 rounded-md shadow-sm hover:bg-blue-700"
          >
          <a
              href="/dashboard"
            >
              Create an Assistant
            </a>
            </Button>
          </div>
          <div className="mx-auto">
          <Image
          alt="Dashboard preview"
          className="mx-auto"
          height="400"
          src="/Demo.svg"
          style={{
            aspectRatio: "400/400",
            objectFit: "cover",
          }}
          width="800"
        />
          </div>
        </section>
        <section className="bg-gray-100 py-12 text-center">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center text-blue-600">Brands that Love Us</h2>
            
            <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
            <Image
              alt="Mendiata Hotel"
              className="h-auto w-auto object-contain"
              height="50"
              src="/mendiata.png"
              style={{
                aspectRatio: "150/50",
                objectFit: "cover",
              }}
              width="60"
            />
            <Image
              alt="La Palm Royal Beach Hotel"
              className="h-auto w-auto object-contain"
              height="50"
              src="/logo-head.png"
              style={{
                aspectRatio: "100/100",
                objectFit: "cover",
              }}
              width="60"
            />
            <Image
              alt="Labadi Beach Hotel"
              className="h-auto w-auto object-contain"
              height="100"
              src="/Labadi-logo.png"
              style={{
                aspectRatio: "150/50",
                objectFit: "cover",
              }}
              width="150"
            />
            <Image
              alt="Kempinski"
              className="h-auto w-auto object-contain"
              height="50"
              src="/Kempiski.png"
              style={{
                aspectRatio: "150/50",
                objectFit: "cover",
              }}
              width="150"
            />
            <Image
              alt="Accra City Hotel"
              className="h-auto w-auto object-contain"
              height="50"
              src="/accracity-logo.png"
              style={{
                aspectRatio: "150/50",
                objectFit: "cover",
              }}
              width="150"
            />
            <Image
              alt="Movenpick Hotel" 
              className="h-auto w-auto object-contain"
              height="50"
              src="/movenpick.png"
              style={{
                aspectRatio: "150/50",
                objectFit: "cover",
              }}
              width="150"
            />
            
          </div>
            </div>
        </section>
        <section className="py-12 text-center">         
        </section>
        <section className="bg-gray-100 py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">How Hotels use Intelli</h2>
            <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-3">
              <div>
                <div className="mx-auto h-12 w-12" />
                <h3 className="mt-4 text-xl font-semibold">Weekly & Monthly Insights:</h3>
                <p className="mt-2 text-sm">Elevate Report Quality, Minimize Time Investment</p>
              </div>
              <div>
                <div className="mx-auto h-12 w-12" />
                <h3 className="mt-4 text-xl font-semibold">Swift Responses to Inquiries:</h3>
                <p className="mt-2 text-sm">Instantly Address Questions with your company Data</p>
              </div>
              <div>
                <div className="mx-auto h-12 w-12" />
                <h3 className="mt-4 text-xl font-semibold">Effective Escalation Management:</h3>
                <p className="mt-2 text-sm">
                  Empower Teams, Managers, and hotel departments with access to issues escalated beyond the assistant.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">What advantages does our software offer?</h2>
            <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h3 className="text-xl font-semibold">Manage your customer service efficiently, save time</h3>
                <ul className="mt-2 list-disc pl-5 text-sm">
                  <li>Streamline Support Processes for Swift Resolution</li>
                  <li>Optimize Resources</li>
                  <li>Utilize Advanced Algorithms</li>
                  <li>Integrate with existing tools and platforms</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Optimize your operations by reducing expenses</h3>
                <ul className="mt-2 list-disc pl-5 text-sm">
                  <li>Cut down on manpower</li>
                  <li>Reduce overhead costs</li>
                  <li>Minimize training expenses</li>
                  <li>Maintain high-quality service and reduce delays</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">What Our Customers Say</h2>
            <div className="mt-6 flex justify-center space-x-4">
            <Reviews/>
              </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">Frequently Asked Questions</h2>
            <div className="mt-8 max-w-2xl mx-auto">
              <div className="mt-4">
                <h3 className="text-lg font-semibold">Can I have multiple employees on the same plan?</h3>
                <p className="mt-2 text-sm">
                  These are the questions that are commonly asked by our users, so we compiled them for you to find
                  answers easily.
                </p>
              </div>
              <div className="mt-4">
                <h3 className="text-lg font-semibold">How is my usage calculated?</h3>
                <p className="mt-2 text-sm">
                  These are the questions that are commonly asked by our users, so we compiled them for you to find
                  answers easily.
                </p>
              </div>
              <div className="mt-4">
                <h3 className="text-lg font-semibold">What payment methods are allowed?</h3>
                <p className="mt-2 text-sm">
                  We embrace the global nature of business and hence use Credit cards. If in the near future more
                  payment methods are added, we shall issue a statement informing you of the change.
                </p>
              </div>
            </div>
            <div className="mt-8 text-center">
              <Button variant="outline">View more</Button>
            </div>
          </div>
        </section>
      </main>

      <footer className="w-full bg-white-500">
        <div className="container-fluid ">
          <p className="text-sm text-center text-gray-900">Need help? Get in touch with us.</p>
          <p className="mt-2 text-xs text-center text-gray-900">
            Terms of Use | Privacy Notice | Data Policy | Socials | © IntelliConcierge 2024
          </p>
        </div>
      </footer>
    </div>
  )
}