/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3Ou93NEzRjT
 */
import { Button } from "@/components/ui/button";
import { Navbar } from "@/components/navbar";
import {
  CardTitle,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

import Image from "next/image";
import demoImage from "@/public/Demo.svg";
import mendiata from "@/public/mendiata.png";
import labadi from "@/public/Labadi-logo.png";
import aquasafari from "@/public/Aqua-Safari-Logo.png";
import kempinski from "@/public/Kempiski.png";
import accraCity from "@/public/accracity-logo.png";
import movenpick from "@/public/movenpick.png";
import pinkImage from "@/public/pink.png";
import yellowImage from "@/public/yello.png";
import Pie from "@/public/piechart.png";

import Reviews from "@/components/component/reviews";

export function Home() {
  return (
    <div className="relative">
      <Navbar />
      <main className="pt-16">
        <section className="container mx-auto mt-8 px-4">
          <h1 className="text-3xl font-thin text-center text-grey-400">
            Intelli Concierge
          </h1>
          <p className="mt-4 text-center text-6xl font-bold text-blue-600 mb-8 bg-clip-text bg-gradient-to-r from-blue-500 to-teal-400">
            Automate customer support responses.
          </p>
          <p className="text-center text-lg font-bold font-medium text-gray-800">
            Improve customer experience by automating responses to frequently
            asked questions. Handle responses across 3 different channels
            seamlessly with one platform. All this power is available at an
            affordable price.
          </p>
          <div className="mt-6 flex justify-center space-x-4">
            <Button className="px-6 py-3 text-md font-medium text-white bg-gray-800 rounded-md shadow-sm hover:bg-gray-900">
              <a href="/demo">See it on your website</a>
            </Button>
            <Button className="px-6 py-3 text-md font-medium text-white bg-blue-600 rounded-md shadow-sm hover:bg-blue-700">
              <a href="/dashboard">Create an Assistant</a>
            </Button>
          </div>
          <div className="mx-auto">
            <Image alt="Preview Demo" className="mx-auto" src={demoImage} />
          </div>
        </section>
        <section className="bg-gray-100 py-12 text-center  shadow-lg rounded-xl">
          <div className="container mx-auto px-4 border">
            <h2 className="text-3xl font-bold text-center text-blue-600">
              Brands that Love Us
            </h2>

            <div className="py-12 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-6 gap-4">
              <Image
                alt="La Palm Royal Beach Hotel"
                className="rounded-lg"
                src={aquasafari}
              />
              <Image
                alt="Mendiata Hotel"
                className="rounded-lg"
                src={mendiata}
                height={120}
              />
              <Image
                alt="Labadi Beach Hotel"
                className="rounded-lg"
                src={labadi}
              />
              <Image alt="Kempinski" className="rounded-lg" src={kempinski} />
              <Image
                alt="Accra City Hotel"
                className="rounded-lg"
                src={accraCity}
              />
              <Image
                alt="Movenpick Hotel"
                className="rounded-lg"
                src={movenpick}
              />
            </div>
          </div>
        </section>
        <section className="py-12 text-center"></section>
        <section className="py-12 relative">
          <Image
            alt="Bg Pink"
            className="absolute top-1/2 right-0 transform -translate-y-1/2 w-60 h-60 bg-cover bg-center filter blur-md z-0"
            style={{ backgroundImage: `url(${pinkImage})` }}
            src={pinkImage}
          />
          <div className="flex justify-center mb-4">
            <Badge>Use Cases</Badge>
          </div>
          <div className="container mx-auto px-4">
            <h2 className="text-6xl font-bold text-center">
              How Hotels use Intelli
            </h2>
            <div className="mt-20 grid grid-cols-1 gap-4 md:grid-cols-3 md:gap-8">
              <Image
                alt="Weekly & Monthly Insights"
                className="absolute top-20 left-0 w-48 h-48 bg-cover bg-center filter  z-0"
                style={{ backgroundImage: `url(${Pie})` }}
                src={Pie}
              />
              <Card className="bg-[#007fff] bg-opacity-35">
                <CardContent className="p-6 space-y-2 backdrop-blur-lg rounded-lg">
                  <div className="text-sm">
                    <CardTitle>Weekly & Monthly Insights:</CardTitle>
                  </div>
                  <div>
                    <p className="text-sm font-medium">
                      Elevate Report Quality, Minimize Time Investment
                    </p>
                  </div>
                </CardContent>
              </Card>

              <Card className="bg-[#ACD4FF] bg-opacity-85">
                <Image
                  alt="Swift AI Responses"
                  className="absolute transform -translate-x-1/2 -translate-y-1/2 w-40 h-40 bg-cover bg-center filter blur-sm z-0"
                  style={{ backgroundImage: `url(${yellowImage})` }}
                  src={yellowImage}
                />
                <CardContent className="p-6 space-y-2 backdrop-blur-lg rounded-lg">
                  <div className="text-sm">
                    <CardTitle>Swift Responses to Inquiries:</CardTitle>
                  </div>
                  <div>
                    <p className="text-sm font-medium">
                      Instantly Address Questions with your company Data
                    </p>
                  </div>
                </CardContent>
              </Card>
              <Card className="bg-[#027EFE] bg-opacity-60">
                <CardContent className="p-6 space-y-2 backdrop-blur-lg rounded-lg">
                  <div className="text-sm">
                    <CardTitle>Effective Escalation Management:</CardTitle>
                  </div>
                  <div>
                    <p className="text-sm font-medium">
                      Empower Teams, Managers, and hotel departments with access
                      to issues escalated beyond the assistant.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 ">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">
              What advantages does our software offer?
            </h2>
            <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h3 className="text-xl font-semibold">
                  Manage your customer service efficiently, save time
                </h3>
                <ul className="mt-2 list-disc pl-5 text-sm">
                  <li>Streamline Support Processes for Swift Resolution</li>
                  <li>Optimize Resources</li>
                  <li>Utilize Advanced Algorithms</li>
                  <li>Integrate with existing tools and platforms</li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-semibold">
                  Optimize your operations by reducing expenses
                </h3>
                <ul className="mt-2 list-disc pl-5 text-sm">
                  <li>Cut down on manpower</li>
                  <li>Reduce overhead costs</li>
                  <li>Minimize training expenses</li>
                  <li>Maintain high-quality service and reduce delays</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">
              What Our Customers Say
            </h2>
            <div className="mt-6 flex justify-center space-x-4">
              <Reviews />
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-3xl font-bold text-center">
              Frequently Asked Questions
            </h2>
            <div className="mt-8 max-w-2xl mx-auto">
              <div className="mt-4">
                <h3 className="text-lg font-semibold">
                  Can I have multiple employees on the same plan?
                </h3>
                <p className="mt-2 text-sm">
                  These are the questions that are commonly asked by our users,
                  so we compiled them for you to find answers easily.
                </p>
              </div>
              <div className="mt-4">
                <h3 className="text-lg font-semibold">
                  How is my usage calculated?
                </h3>
                <p className="mt-2 text-sm">
                  These are the questions that are commonly asked by our users,
                  so we compiled them for you to find answers easily.
                </p>
              </div>
              <div className="mt-4">
                <h3 className="text-lg font-semibold">
                  What payment methods are allowed?
                </h3>
                <p className="mt-2 text-sm">
                  We embrace the global nature of business and hence use Credit
                  cards. If in the near future more payment methods are added,
                  we shall issue a statement informing you of the change.
                </p>
              </div>
            </div>
            <div className="mt-8 text-center">
              <Button variant="outline">View more</Button>
            </div>
          </div>
        </section>
      </main>

      <footer className="w-full bg-white-500">
        <div className="container-fluid ">
          <p className="text-sm text-center text-gray-900">
            Need help? Get in touch with us.
          </p>
          <p className="mt-2 text-xs text-center text-gray-900">
            Terms of Use | Privacy Notice | Data Policy | Socials | ©
            IntelliConcierge 2024
          </p>
        </div>
      </footer>
    </div>
  );
}
