/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rb4snz5lJM5
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Products() {
  return (
    <div className="bg-[#f8f9fa] min-h-screen">
      <nav className="bg-white px-6 py-4 shadow">
        <div className="flex justify-between items-center">
          <div className="flex items-center space-x-4">
            <img alt="Intelli Concierge Logo" className="h-8" src="/placeholder.svg" />
            <a className="text-sm font-medium text-gray-700 hover:text-gray-900" href="#">
              Products
            </a>
            <a className="text-sm font-medium text-gray-700 hover:text-gray-900" href="#">
              Pricing
            </a>
            <a className="text-sm font-medium text-gray-700 hover:text-gray-900" href="#">
              Resources
            </a>
            <a className="text-sm font-medium text-gray-700 hover:text-gray-900" href="#">
              Company
            </a>
          </div>
          <div className="flex items-center space-x-2">
            <Button className="bg-transparent text-blue-600 hover:bg-blue-50">Book A Demo</Button>
            <Button className="bg-blue-600 text-white hover:bg-blue-700">Get Started</Button>
          </div>
        </div>
      </nav>
      <header className="text-center py-20">
        <h1 className="text-4xl font-bold text-gray-900 leading-snug">
          We are building Africa’s most robust suite
          <br />
          of AI-powered tools for businesses.
        </h1>
        <p className="mt-6 text-lg text-gray-700 max-w-3xl mx-auto">
          Our first product is called Intelli Concierge, for customer experience, a knowledgeable, humorous and
          professional speech conversational AI.
          <br />
          We are set to release more products down the line;
        </p>
        <p className="mt-4 text-lg text-gray-700 max-w-3xl mx-auto italic">
          Experience the power of Ai with your own eyes and ears
        </p>
        <div className="mt-8 mx-auto max-w-xs">
          <form className="flex flex-col space-y-4">
            <Input placeholder="Your Email Address" type="email" />
            <Button className="bg-blue-600 text-white hover:bg-blue-700">Book demo</Button>
          </form>
        </div>
      </header>
    </div>
  )
}
