/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5hUeUAXMQcH
 */

import { JSX, SVGProps } from "react"
import { Navbar } from "@/components/navbar"
import { DynamicBlog } from "@/components/component/blogComponent"


export function Resources() {
  return (
    <div className="bg-white min-h-screen relative">
      <Navbar />
      <DynamicBlog />
    </div>
  )
}



