/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KE6K3dBRn0w
 */
import { Avatar } from "@/components/ui/avatar"
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import Image from "next/image"

export default function Reviews() {
  return (
    <Carousel className="w-full max-w-lg">
      <CarouselContent className="h-48">
        <CarouselItem>
          <div className="py-2">
            <Card>
              <CardContent className="p-6 pt-6 space-y-2">
                <div>
                  <p className="text-sm font-medium">
                    Intelli is Mind-blowing! Our Hotel Revenue has increased by a margin of 20% since we switched to using them.
                  </p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="flex items-center space-x-2">
                    <Avatar className="w-8 h-8">
                      <Image
                        alt="Hanno Barkhoff"
                        className="rounded-full"
                        height="32"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width="32"
                      />
                    </Avatar>
                    <div className="text-sm">
                      <CardTitle>Hanno Barkhoff</CardTitle>
                      <CardDescription>General Manager</CardDescription>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-2">
            <Card>
              <CardContent className="space-y-2">
                <div>
                  <p className="text-sm font-medium">
                    The service was exceptional, and the staff was incredibly helpful. I would definitely recommend this
                    place to my friends and family.
                  </p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="flex items-center space-x-2">
                    <Avatar className="w-8 h-8">
                      <Image
                        alt="Alice Chen"
                        className="rounded-full"
                        height="32"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width="32"
                      />
                    </Avatar>
                    <div className="text-sm">
                      <CardTitle>Alice Chen</CardTitle>
                      <CardDescription>Customer</CardDescription>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-2">
            <Card>
              <CardContent className="space-y-2">
                <div>
                  <p className="text-sm font-medium">
                    I had a fantastic experience at the spa. The massage was incredibly relaxing, and the ambiance was
                    perfect.
                  </p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="flex items-center space-x-2">
                    <Avatar className="w-8 h-8">
                      <Image
                        alt="David Johnson"
                        className="rounded-full"
                        height="32"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width="32"
                      />
                    </Avatar>
                    <div className="text-sm">
                      <CardTitle>David Johnson</CardTitle>
                      <CardDescription>Spa Enthusiast</CardDescription>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
