/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FjoN9IRGfpj
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Signup() {
  return (
    <div key="1" className="flex min-h-screen bg-[#E5F4FF]">
      <div className="m-auto w-full max-w-md p-6 bg-white rounded-lg shadow-md">
        <h1 className="text-black text-xl font-semibold text-gray-700 text-center">Create a free account</h1>
        <form className="mt-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col">
              <label className="text-sm font-medium text-gray-700" htmlFor="first-name">
                First Name
              </label>
              <Input id="first-name" placeholder="John" />
            </div>
            <div className="flex flex-col">
              <label className="text-sm font-medium text-gray-700" htmlFor="last-name">
                Last Name
              </label>
              <Input id="last-name" placeholder="Doe" />
            </div>
          </div>
          <div className="mt-4 flex flex-col">
            <label className="text-sm font-medium text-gray-700" htmlFor="company-name">
              Company Name
            </label>
            <Input id="company-name" placeholder="Aqua Safari" />
          </div>
          <div className="mt-4 flex flex-col">
            <label className="text-sm font-medium text-gray-700" htmlFor="role">
              Role in Company
            </label>
            <Input id="role" placeholder="Manager" />
          </div>
          <div className="mt-4 flex flex-col">
            <label className="text-sm font-medium text-gray-700" htmlFor="email">
              Work Email
            </label>
            <Input id="email" placeholder="youremail@company.com" type="email" />
          </div>
          <div className="mt-4 flex flex-col">
            <label className="text-sm font-medium text-gray-700" htmlFor="password">
              Password
            </label>
            <Input id="password" placeholder="************" type="password" />
          </div>
          <div className="mt-6">
            <Button className="w-full">Signup</Button>
          </div>
        </form>
        <div className="mt-4 text-center">
          <p className="text-sm">
            Already have an account?
            <Link className="text-blue-600" href="#">
              Log In
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
