/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cJuUudSVSRo
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Signin() {
  return (
    <div className="flex min-h-screen flex-col bg-[#E6F4FF]">
      <div className="mx-auto my-auto w-full max-w-md rounded-lg bg-white p-8">
        <h1 className="text-center text-2xl font-semibold">Welcome back to Intelli</h1>
        <form className="mt-4 space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700" htmlFor="email">
              Work Email
            </label>
            <Input id="email" placeholder="youremail@company.com" type="email" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700" htmlFor="password">
              Password
            </label>
            <Input id="password" placeholder="**********" type="password" />
          </div>
          <Button className="w-full  bg-blue-600 text-white" variant="default">
            Login
          </Button>
        </form>
        <div className="mt-4 text-center">
          <span className="text-sm text-gray-500">Don&apos;t have an account? </span>
          <a className="text-sm font-medium text-blue-600" href="/auth/register">
            Create One
          </a>
        </div>
      </div>
    </div>
  )
}
